name: Continuos Integration with Github actions

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
   
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application JAR
      working-directory: ./rest-spring_boot/rest-com-spring-boot-e-java
      run:  mvn clean package

    - name: Docker Compose Build
      working-directory: ./rest-spring_boot
      run:  docker compose build

    - name: Push to Docker Hub Container Registry
      run: 
        docker tag ${{ secrets.DOCKER_USERNAME }}/rest-com-springboot:latest ${{ secrets.DOCKER_USERNAME }}/rest-com-springboot:${{ github.run_id }}

        docker push ${{ secrets.DOCKER_USERNAME }}/rest-com-springboot:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-com-springboot:latest
